//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Devices.Applications.PredictiveMaintenance.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.Devices.Applications.PredictiveMaintenance.Web.App_GlobalResource" +
                            "s.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictive maintenance.
        /// </summary>
        public static string BrandingTitle {
            get {
                return ResourceManager.GetString("BrandingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure IoT.
        /// </summary>
        public static string BrandingTitlePrefix {
            get {
                return ResourceManager.GetString("BrandingTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start simulation.
        /// </summary>
        public static string ButtonLabelStartSimulation {
            get {
                return ResourceManager.GetString("ButtonLabelStartSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop simulation.
        /// </summary>
        public static string ButtonLabelStopSimulation {
            get {
                return ResourceManager.GetString("ButtonLabelStopSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine #1.
        /// </summary>
        public static string ChartLabelEngine1 {
            get {
                return ResourceManager.GetString("ChartLabelEngine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine #2.
        /// </summary>
        public static string ChartLabelEngine2 {
            get {
                return ResourceManager.GetString("ChartLabelEngine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation in progress.
        /// </summary>
        public static string IndicatorLabelStarted {
            get {
                return ResourceManager.GetString("IndicatorLabelStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string IndicatorLabelStarting {
            get {
                return ResourceManager.GetString("IndicatorLabelStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation stopped.
        /// </summary>
        public static string IndicatorLabelStopped {
            get {
                return ResourceManager.GetString("IndicatorLabelStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        public static string IndicatorLabelStopping {
            get {
                return ResourceManager.GetString("IndicatorLabelStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string LinkLabelDashboard {
            get {
                return ResourceManager.GetString("LinkLabelDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support.
        /// </summary>
        public static string LinkLabelHelpAndSupport {
            get {
                return ResourceManager.GetString("LinkLabelHelpAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give feedback.
        /// </summary>
        public static string LinkLabelHelpGiveFeedback {
            get {
                return ResourceManager.GetString("LinkLabelHelpGiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string LinkLabelSignOut {
            get {
                return ResourceManager.GetString("LinkLabelSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure IoT - Predictive maintenance.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string PageTitleDashboard {
            get {
                return ResourceManager.GetString("PageTitleDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft map.
        /// </summary>
        public static string TileHeadingAircraftMap {
            get {
                return ResourceManager.GetString("TileHeadingAircraftMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles.
        /// </summary>
        public static string TileHeadingCycles {
            get {
                return ResourceManager.GetString("TileHeadingCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Useful Life (RUL).
        /// </summary>
        public static string TileHeadingRul {
            get {
                return ResourceManager.GetString("TileHeadingRul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Useful Life (RUL) history.
        /// </summary>
        public static string TileHeadingRulHistory {
            get {
                return ResourceManager.GetString("TileHeadingRulHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor 11.
        /// </summary>
        public static string TileHeadingSensor11 {
            get {
                return ResourceManager.GetString("TileHeadingSensor11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor 14.
        /// </summary>
        public static string TileHeadingSensor14 {
            get {
                return ResourceManager.GetString("TileHeadingSensor14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor 15.
        /// </summary>
        public static string TileHeadingSensor15 {
            get {
                return ResourceManager.GetString("TileHeadingSensor15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor 9.
        /// </summary>
        public static string TileHeadingSensor9 {
            get {
                return ResourceManager.GetString("TileHeadingSensor9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor history.
        /// </summary>
        public static string TileHeadingSensorHistory {
            get {
                return ResourceManager.GetString("TileHeadingSensorHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In cycles.
        /// </summary>
        public static string TileHeadingSubheadingInCycles {
            get {
                return ResourceManager.GetString("TileHeadingSubheadingInCycles", resourceCulture);
            }
        }
    }
}
