// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BatchWebServiceResult
    {
        /// <summary>
        /// Initializes a new instance of the BatchWebServiceResult class.
        /// </summary>
        public BatchWebServiceResult() { }

        /// <summary>
        /// Initializes a new instance of the BatchWebServiceResult class.
        /// </summary>
        public BatchWebServiceResult(string state = default(string), int? completedItemCount = default(int?), int? totalItemCount = default(int?), IList<WebServiceResult> batchExecutionResults = default(IList<WebServiceResult>))
        {
            State = state;
            CompletedItemCount = completedItemCount;
            TotalItemCount = totalItemCount;
            BatchExecutionResults = batchExecutionResults;
        }

        /// <summary>
        /// State of the execution. Can be of the following values:
        /// - Pending: The batch execution was submitted but is not yet
        /// scheduled.
        /// Ready: The batch execution was submitted and can be executed.
        /// InProgress: The batch execution is currently being processed.
        /// Complete: The batch execution has been completed. Possible values
        /// include: 'pending', 'inProgress', 'ready', 'complete'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// Number of completed items in this batch operation.
        /// </summary>
        [JsonProperty(PropertyName = "completedItemCount")]
        public int? CompletedItemCount { get; set; }

        /// <summary>
        /// Number of total items in this batch operation.
        /// </summary>
        [JsonProperty(PropertyName = "totalItemCount")]
        public int? TotalItemCount { get; set; }

        /// <summary>
        /// The responses of the individual executions.
        /// </summary>
        [JsonProperty(PropertyName = "batchExecutionResults")]
        public IList<WebServiceResult> BatchExecutionResults { get; set; }

    }
}
